# Generated by Django 2.2.7 on 2021-07-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checklist_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Delar_Name', models.CharField(max_length=200)),
                ('var1', models.CharField(max_length=200)),
                ('var2', models.CharField(max_length=200)),
                ('var3', models.CharField(max_length=200)),
                ('var4', models.CharField(max_length=200)),
                ('var5', models.CharField(max_length=200)),
                ('var6', models.CharField(max_length=200)),
                ('var7', models.CharField(max_length=200)),
                ('var8', models.CharField(max_length=200)),
                ('var9', models.CharField(max_length=200)),
                ('var10', models.CharField(max_length=200)),
                ('var11', models.CharField(max_length=200)),
                ('var12', models.CharField(max_length=200)),
                ('var13', models.CharField(max_length=200)),
                ('var14', models.CharField(max_length=200)),
                ('var15', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
