# Generated by Django 2.2.7 on 2021-07-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklistapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='checklist_data',
            new_name='s21',
        ),
    ]
